// apps/web ESLint config.
//
// Resolved and used whenever ESLint runs with this directory as its working
// directory — flat config has no automatic directory cascading, so CWD decides
// which config file applies. That's `turbo lint`/CI (runs this package's own
// `lint` script from inside this directory) and, since CR-010, lint-staged's
// pre-commit hook too (root `package.json`'s `apps/web/**/*.{ts,tsx,js,jsx}`
// entry runs `pnpm --filter web exec eslint --fix`, which sets CWD here for
// exactly this reason). The repo-root `pnpm lint:root` still uses
// ../../eslint.config.mjs instead, which ignores apps/**/packages/** so it
// doesn't double-cover this file. See docs/changelog.md (CR-002, CR-010).
//
// eslint-config-next does not yet ship a prebuilt flat config export, so we
// bridge its legacy-style shareable configs via FlatCompat, per Next's own
// documented setup for ESLint 9 + flat config.
import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    // next-env.d.ts is regenerated by `next build`/`next dev` itself (its own
    // header says not to edit it) and uses a triple-slash reference by Next's
    // own convention — that's expected here, not a violation to fix.
    ignores: ['.next/**', 'node_modules/**', 'next-env.d.ts'],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
];

export default eslintConfig;
