// apps/web ESLint config.
//
// Resolved and used whenever ESLint runs with this directory as its working
// directory — flat config has no automatic directory cascading, so CWD decides
// which config file applies. That's `turbo lint`/CI (runs this package's own
// `lint` script from inside this directory) and, since CR-010, lint-staged's
// pre-commit hook too (root `package.json`'s `apps/web/**/*.{ts,tsx,js,jsx}`
// entry runs `pnpm --filter web exec eslint --fix`, which sets CWD here for
// exactly this reason). The repo-root `pnpm lint:root` still uses
// ../../eslint.config.mjs instead, which ignores apps/**/packages/** so it
// doesn't double-cover this file. See docs/changelog.md (CR-002, CR-010).
//
// eslint-config-next does not yet ship a prebuilt flat config export, so we
// bridge its legacy-style shareable configs via FlatCompat, per Next's own
// documented setup for ESLint 9 + flat config.
import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    // next-env.d.ts is regenerated by `next build`/`next dev` itself (its own
    // header says not to edit it) and uses a triple-slash reference by Next's
    // own convention — that's expected here, not a violation to fix.
    ignores: ['.next/**', 'node_modules/**', 'next-env.d.ts'],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      // docs/design.md §14 (CR-063): feature code uses a design token
      // (`bg-bg-raised`, `text-text-secondary`, ...) from packages/ui's
      // Tailwind theme, never a raw hex literal — inline style, a Tailwind
      // arbitrary value (`bg-[#123456]`), or anywhere else. The tokens
      // themselves live in packages/ui/src/tokens.css, a CSS file this rule
      // (JS/TS-only) never touches, so it can't flag its own source of truth.
      'no-restricted-syntax': [
        'error',
        {
          selector: 'Literal[value=/#[0-9a-fA-F]{3,8}\\b/]',
          message:
            'Raw hex colors are not allowed here — use a design token from packages/ui (docs/design.md §3).',
        },
        {
          selector: 'TemplateElement[value.raw=/#[0-9a-fA-F]{3,8}\\b/]',
          message:
            'Raw hex colors are not allowed here — use a design token from packages/ui (docs/design.md §3).',
        },
      ],
      // CR-056 (ADR-010, `.claude/rules/maps.md`): only packages/maps-2gis
      // may import a 2GIS SDK package, and only the single composition
      // point below may import packages/maps-2gis itself
      // (`.claude/rules/architecture.md`'s "one composition point ...
      // to wire the concrete adapter"). The `*2gis*` glob also matches the
      // bare workspace specifier `maps-2gis`, not just a vendor SDK name —
      // that's intentional here, since importing the workspace package
      // directly is exactly what's restricted to one file (see the
      // `files`-scoped override below, ADR-020).
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['*2gis*'],
              message:
                'Only packages/maps-2gis may import a 2GIS SDK package (ADR-010, .claude/rules/maps.md).',
            },
          ],
        },
      ],
    },
  },
  {
    // ADR-020: the one composition point allowed to import `maps-2gis`
    // directly, to wire its concrete 2GIS MapGL renderer behind
    // `maps-core`'s provider-neutral `MapRenderer` interface. No other
    // apps/web module gets this exception.
    files: ['src/lib/maps/create-map-renderer.ts'],
    rules: {
      'no-restricted-imports': 'off',
    },
  },
];

export default eslintConfig;
