// apps/web ESLint config.
//
// Resolved and used only when ESLint runs with this directory as its working
// directory (i.e. `turbo lint` / CI, which run each workspace's own `lint`
// script from inside that workspace) — flat config has no automatic directory
// cascading, so this file is NOT picked up by the repo-root `pnpm lint:root` or
// by lint-staged's pre-commit `eslint --fix` (both run with CWD at the repo
// root and use ../../eslint.config.mjs instead, which ignores apps/**/packages/**
// for exactly this reason). See docs/changelog.md (CR-002) and KI-012.
//
// eslint-config-next does not yet ship a prebuilt flat config export, so we
// bridge its legacy-style shareable configs via FlatCompat, per Next's own
// documented setup for ESLint 9 + flat config.
import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    // next-env.d.ts is regenerated by `next build`/`next dev` itself (its own
    // header says not to edit it) and uses a triple-slash reference by Next's
    // own convention — that's expected here, not a violation to fix.
    ignores: ['.next/**', 'node_modules/**', 'next-env.d.ts'],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
];

export default eslintConfig;
