import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Script from 'next/script';
import { ToastProvider } from 'ui';
import { AppHeader } from '@/components/site/AppHeader';
import { BottomTabBar } from '@/components/site/BottomTabBar';
import { SiteChrome } from '@/components/site/SiteChrome';
import { filterEnabled } from '@/lib/cabinet/feature-flags';
import { ORGANIZER_NAV_ITEMS } from '@/lib/cabinet/organizer-nav';
import { PARTICIPANT_NAV_ITEMS } from '@/lib/cabinet/participant-nav';
import { SessionProvider } from '@/lib/auth/session-context';
import { THEME_INIT_SCRIPT } from '@/lib/theme/theme';
import './globals.css';

// CR-146 (KI-074): every face is self-hosted from `src/fonts/` (SIL OFL,
// `src/fonts/licenses/`) through `next/font/local`, so `next build` no longer
// downloads anything from Google Fonts. The .woff2 files are generated by
// `src/fonts/build-fonts.sh` — same `latin` + `cyrillic` glyph ranges, same
// weights and every OpenType feature (`locl`, `tnum`) that `next/font/google`
// served before. A new weight means re-running that script, not a new import.
//
// docs/design.md §4: Golos Text (Cyrillic-first grotesque) for UI text, IBM
// Plex Mono for labels and tabular/data text (dates, units, IDs) — the label
// role Sofia Sans Condensed held until CR-152 (ADR-026). `variable` binds the
// loaded webfont to the CSS custom property packages/ui's tokens.css reads as
// its `--font-sans`/`--font-mono` source (see tokens.css's
// `var(--font-golos, ...)` fallback).
const golosText = localFont({
  src: [
    { path: '../fonts/GolosText-400.woff2', weight: '400', style: 'normal' },
    { path: '../fonts/GolosText-500.woff2', weight: '500', style: 'normal' },
    { path: '../fonts/GolosText-600.woff2', weight: '600', style: 'normal' },
    // 800: the wordmark only (CR-121).
    { path: '../fonts/GolosText-800.woff2', weight: '800', style: 'normal' },
  ],
  variable: '--font-golos',
  display: 'swap',
});

const ibmPlexMono = localFont({
  src: [
    { path: '../fonts/IBMPlexMono-400.woff2', weight: '400', style: 'normal' },
    { path: '../fonts/IBMPlexMono-500.woff2', weight: '500', style: 'normal' },
  ],
  variable: '--font-plex-mono',
  display: 'swap',
});

// ADR-024: `font-title` — the display role (ride title) and `h1` only since
// CR-152 (ADR-026, `globals.css`).
const unbounded = localFont({
  src: [
    { path: '../fonts/Unbounded-500.woff2', weight: '500', style: 'normal' },
    { path: '../fonts/Unbounded-600.woff2', weight: '600', style: 'normal' },
    { path: '../fonts/Unbounded-700.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-unbounded',
  display: 'swap',
});

// ADR-024: `font-num` — large tabular metric numerals (route cover,
// `MetricTile`). Weights 700/800 cover the mockup's 30-44px numerals. Sofia
// Sans' default Cyrillic is the Bulgarian form set (в/д/и/т drawn like
// b/g/u/m); the Russian forms come from its `locl` OpenType feature, which
// browsers apply only when the text's language is Russian. That is what
// `<html lang="ru">` below guarantees — do not remove it, and do not set a
// different `lang` on any element rendered in this face.
const sofiaSansExtraCondensed = localFont({
  src: [
    {
      path: '../fonts/SofiaSansExtraCondensed-700.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../fonts/SofiaSansExtraCondensed-800.woff2',
      weight: '800',
      style: 'normal',
    },
  ],
  variable: '--font-sofia-extra-condensed',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Coffee Ride',
  description:
    'Платформа для поиска, организации и участия в групповых велозаездах.',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // `suppressHydrationWarning`: THEME_INIT_SCRIPT adds `.dark` to this
    // element before hydration on purpose, so its `class` legitimately
    // differs from the server HTML (one level deep only — children are
    // still checked).
    <html
      lang="ru"
      suppressHydrationWarning
      className={`${golosText.variable} ${ibmPlexMono.variable} ${unbounded.variable} ${sofiaSansExtraCondensed.variable}`}
    >
      <head>
        <Script
          id="theme-init"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }}
        />
      </head>
      <body>
        {/* docs/design.md §11: "xl (>= 1280): max content width 1200px, centered" —
            one shared cap here rather than repeated per-page, per
            `.claude/context/current-task.md`'s CR-044 finding. Every page's own
            (narrower) container still applies inside it; this only bounds the
            widest screens/layouts (the discovery split view).
            CR-108: `AppHeader` sits outside that cap so its bottom border runs
            the full width of the viewport, and caps its own inner nav instead. */}
        <SessionProvider>
          <ToastProvider>
            {/* CR-132: `SiteChrome` leaves both off on `/organizer/*`,
                which draws its own header and frame. */}
            <SiteChrome
              header={
                <AppHeader
                  participantNavItems={filterEnabled(PARTICIPANT_NAV_ITEMS)}
                  organizerNavItems={filterEnabled(ORGANIZER_NAV_ITEMS)}
                />
              }
            >
              {children}
            </SiteChrome>
            {/* CR-130 (ADR-024): mobile-only, alongside `AppHeader`'s menu. */}
            <BottomTabBar />
          </ToastProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
